//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.JoinLogs = new HashSet<JoinLog>();
            this.RatingLogs = new HashSet<RatingLog>();
        }
    
        public int Id { get; set; }
        public string ActivityName { get; set; }
        public System.DateTime ActivityStartDate { get; set; }
        public int ActivityDuration { get; set; }
        public string ActivityDescription { get; set; }
        public string ActivityStatus { get; set; }
        public int ActivityRating { get; set; }
        public int ActivityTypeId { get; set; }
        public int ActivityPlaceId { get; set; }
        public int ActivityCategoryId { get; set; }
    
        public virtual ActivityPlace ActivityPlace { get; set; }
        public virtual ActivityType ActivityType { get; set; }
        public virtual ActivityCategory ActivityCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoinLog> JoinLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingLog> RatingLogs { get; set; }
    }
}
